#!/usr/bin/env python3
"""Regenerate Atlas/Projects/_registry.md from ~/Projects and the vault's project notes.

Writes only the registry (and optionally metrics.csv rows). Never edits notes.
Usage: scan_projects.py [--vault PATH] [--projects PATH] [--metrics] [--json]
"""
import argparse
import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass, asdict
from datetime import datetime, timezone
from pathlib import Path

SKIP_DIRS = {"Vault", "archive", "resources"}
NOTE_TYPES = {"project", "prd"}


@dataclass
class Repo:
    name: str
    path: str
    archived: bool
    remote: str | None
    last_commit: str | None
    dirty: bool | None


@dataclass
class Note:
    path: str
    title: str
    status: str
    repo: str | None
    kind: str


def git(path: Path, *args: str) -> str | None:
    if not (path / ".git").exists():
        return None
    r = subprocess.run(["git", "-C", str(path), *args], capture_output=True, text=True)
    return r.stdout.strip() if r.returncode == 0 else None


def scan_repo(path: Path, archived: bool) -> Repo:
    remote = git(path, "remote", "get-url", "origin")
    last = git(path, "log", "-1", "--format=%cs")
    status = git(path, "status", "--porcelain")
    return Repo(
        name=path.name,
        path=str(path),
        archived=archived,
        remote=remote or None,
        last_commit=last or None,
        dirty=None if status is None else bool(status),
    )


def scan_repos(root: Path) -> list[Repo]:
    repos = []
    for p in sorted(root.iterdir()):
        if p.is_dir() and p.name not in SKIP_DIRS and not p.name.startswith("."):
            repos.append(scan_repo(p, archived=False))
    archive = root / "archive"
    if archive.is_dir():
        for p in sorted(archive.iterdir()):
            if p.is_dir() and p.name not in SKIP_DIRS and not p.name.startswith("."):
                repos.append(scan_repo(p, archived=True))
    return repos


FM_RE = re.compile(r"\A---\n(.*?)\n---", re.S)


def frontmatter(text: str) -> dict[str, str]:
    m = FM_RE.match(text)
    if not m:
        return {}
    out = {}
    for line in m.group(1).splitlines():
        if ":" in line and not line.startswith((" ", "-")):
            k, v = line.split(":", 1)
            out[k.strip()] = v.strip().strip("'\"")
    return out


def scan_notes(vault: Path) -> list[Note]:
    notes = []
    for p in sorted((vault / "Atlas" / "Projects").rglob("*.md")):
        if "_archive" in p.parts or p.name.startswith("_"):
            continue
        fm = frontmatter(p.read_text())
        if fm.get("type") not in NOTE_TYPES:
            continue
        repo = fm.get("repo")
        notes.append(Note(
            path=str(p.relative_to(vault)),
            title=fm.get("title", p.stem),
            status=fm.get("status", "?"),
            repo=str(Path(repo).expanduser()) if repo else None,
            kind=fm["type"],
        ))
    return notes


def ignored(vault: Path) -> set[str]:
    """Paths listed (one per line, `~` allowed) in Atlas/Projects/_registry-ignore.md are not projects."""
    f = vault / "Atlas" / "Projects" / "_registry-ignore.md"
    if not f.exists():
        return set()
    out = set()
    for line in f.read_text().splitlines():
        line = line.strip().lstrip("-").strip().strip("`")
        if line.startswith("~") or line.startswith("/"):
            out.add(str(Path(line).expanduser()))
    return out


def build(vault: Path, projects: Path) -> dict:
    skip = ignored(vault)
    repos = [r for r in scan_repos(projects) if r.path not in skip]
    notes = scan_notes(vault)
    by_path = {r.path: r for r in repos}
    noted_paths = {n.repo for n in notes if n.repo}
    registered = [(n, by_path[n.repo]) for n in notes if n.repo in by_path]
    missing = [n for n in notes if n.repo and n.repo not in by_path]
    unlinked = [n for n in notes if not n.repo and n.kind == "project"]
    unnoted = [r for r in repos if r.path not in noted_paths]
    return {
        "repos": repos, "notes": notes, "registered": registered,
        "missing": missing, "unlinked": unlinked, "unnoted": unnoted,
    }


def wikilink(note: Note) -> str:
    return f"[[{Path(note.path).stem}]]"


def short(remote: str | None) -> str:
    if not remote:
        return "no remote"
    m = re.search(r"github\.com[:/](.+?)(?:\.git)?$", remote)
    return m.group(1) if m else remote


def render(data: dict, projects: Path) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    rel = lambda p: "~/Projects/" + str(Path(p).relative_to(projects))
    L = [
        "---", "type: generated", "title: Projects registry",
        f"source: {projects}", f"updated: {now}", "---", "",
        "# Projects registry", "",
        "> GENERATED by the `update-vault` skill (`scan_projects.py`). Do not hand-edit.",
        "> Fix drift by editing the project note's `repo:` or `status:` frontmatter, or by moving the folder.", "",
        f"Repos: {len(data['repos'])} · Registered: {len(data['registered'])} · "
        f"Unnoted: {len(data['unnoted'])} · Missing: {len(data['missing'])} · Notes without repo: {len(data['unlinked'])}", "",
        "## Registered", "",
        "| Note | Status | Repo | Remote | Last commit | Dirty |",
        "|---|---|---|---|---|---|",
    ]
    for n, r in data["registered"]:
        status = n.status + (" (folder in archive/)" if r.archived and n.status != "archived" else "")
        dirty = "" if r.dirty is None else ("yes" if r.dirty else "no")
        L.append(f"| {wikilink(n)} | {status} | `{rel(r.path)}` | {short(r.remote)} | {r.last_commit or 'not git'} | {dirty} |")
    L += ["", "## Unnoted repos", "", "Folders under `~/Projects` with no project note pointing at them.", "",
          "| Repo | Remote | Last commit | In archive/ |", "|---|---|---|---|"]
    for r in data["unnoted"]:
        L.append(f"| `{rel(r.path)}` | {short(r.remote)} | {r.last_commit or 'not git'} | {'yes' if r.archived else ''} |")
    L += ["", "## Missing repos", "", "Notes whose `repo:` points at a folder that no longer exists (moved or deleted).", ""]
    L += [f"- {wikilink(n)} → `{n.repo}`" for n in data["missing"]] or ["- none"]
    L += ["", "## Notes without repo", "", "Project notes with no `repo:` field (PRDs are exempt).", ""]
    L += [f"- {wikilink(n)} ({n.status})" for n in data["unlinked"]] or ["- none"]
    return "\n".join(L) + "\n"


def append_metrics(vault: Path, data: dict) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    rows = {
        "repos_total": len(data["repos"]),
        "repos_active": sum(1 for r in data["repos"] if not r.archived),
        "unnoted": len(data["unnoted"]),
        "missing": len(data["missing"]),
    }
    # Metrics live in the runner, not the vault: the vault holds knowledge and the
    # runner holds everything that changes because something ran. ADR 0001.
    with (vault.parent / "runner" / "metrics" / "metrics.csv").open("a") as f:
        for k, v in rows.items():
            f.write(f"{now},projects,{k},{v},ok,\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--vault", default=os.environ.get("HELM_VAULT_ROOT") or "~/Vault")
    ap.add_argument("--projects", default="~/Projects")
    ap.add_argument("--metrics", action="store_true", help="also append counts to runner/metrics/metrics.csv")
    ap.add_argument("--json", action="store_true", help="print drift as JSON instead of a summary")
    a = ap.parse_args()
    vault, projects = Path(a.vault).expanduser(), Path(a.projects).expanduser()
    data = build(vault, projects)
    out = vault / "Atlas" / "Projects" / "_registry.md"
    out.write_text(render(data, projects))
    if a.metrics:
        append_metrics(vault, data)
    if a.json:
        print(json.dumps({
            "unnoted": [asdict(r) for r in data["unnoted"]],
            "missing": [asdict(n) for n in data["missing"]],
            "unlinked": [asdict(n) for n in data["unlinked"]],
            "registered": [{"note": asdict(n), "repo": asdict(r)} for n, r in data["registered"]],
        }, indent=2))
    else:
        print(f"wrote {out}")
        print(f"repos={len(data['repos'])} registered={len(data['registered'])} unnoted={len(data['unnoted'])} "
              f"missing={len(data['missing'])} unlinked={len(data['unlinked'])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
